#!/usr/bin/env node

var detective = require('detective'),
    resolve = require('browser-resolve'),
    fs = require('graceful-fs'),
    path = require('path'),
    async = require('async'),
    debug = require('debug')('browserify-graph'),
    archy = require('archy');

if (process.argv.length < 3) {
    console.error('Usage: browserify-graph <file>');
    console.error('Prints out a graph of all modules a file depends on');
    console.error('Uses the same dependency resolution as browserify');
    process.exit(1);
}

var IS_CORE = /^[^\\\/]+$/,
    file = path.resolve(process.argv[2]),
    dependenciesByFile = {},
    edgeId = 0,
    nodes = [],
    edges = [],
    basedir = path.dirname(file);

get(null, file, done);


function get(parentNodeId, file, callback) {
    debug("[get] " + file);
    if (IS_CORE.test(file)) {
        return callback(null, { label: file + ' - builtin', nodes: [] });
    }

    file = path.resolve(file);

    if (file in dependenciesByFile) {
      debug("[get] Ignoring second call to get for " + file);
      return callback(null, dependenciesByFile[file]);
    }

    dependenciesByFile[file] = {};
    var thisNodeId = path.relative(process.cwd(), file);
    var thisNode = {
      id: thisNodeId,
      label: thisNodeId,
      size: 1,
    };
    nodes.push(thisNode);

    if (parentNodeId) {
      edges.push({
        id: "e" + (++edgeId),
        source: parentNodeId,
        target: thisNodeId,
      });
    }
    fs.readFile(file, 'utf8', read);

    function read(err, contents) {
        if (err) {
            return callback(err);
        }

        var requires = detective(contents);
        debug("[get/read] Got " + requires.length + " requires for " + file);
        thisNode.size = requires.length;
        async.map(requires, getDep, gotDeps);
    }

    function getDep(name, callback) {
        debug("[get/getDep] Getting additional dependency " + name);
        resolve(name, { filename: file }, resolved);

        function resolved(err, p) {
            if (err) {
                return callback(err);
            }

            return get(thisNodeId, p, callback);
        }
    }

    function gotDeps(err, deps) {
        if (err) {
            return callback(err);
        }

        Object.assign(dependenciesByFile[file], { label: path.relative(basedir, file), nodes: deps });
        callback(null, dependenciesByFile[file]);
    }
}

function done(err, data) {
    debug("[done] All done!");
    if (err) throw err;
    console.log(JSON.stringify({nodes: nodes, edges: edges}));
}
